name: lottery_3d_app
description: "福彩3D/排列三 投注助手"
publish_to: 'none'
version: 8.0.0+7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  provider: 6.1.2
  sqflite: 2.3.3+2
  path: 1.9.0
  path_provider: 2.1.4
  share_plus: 7.2.2
  intl: 0.19.0
  http: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
